{% set name = "pyls-memestra" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 495611a910c1530887fe2075c95cd2dfeb088d8deda7ba264e10550db1c7fb00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - pyyaml
    - python-language-server
    - memestra
    - deprecator

test:
  imports:
    - pyls_memestra

about:
  home: https://github.com/QuantStack/pyls-memestra/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Memestra plugin for the Python Language Server

extra:
  recipe-maintainers:
    - marimeireles
    - SylvainCorlay
