{% set name = "pyls-memestra" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 860223ff64740415706407f4e84b365bb6fc2f4409904a4447ce0eeab4a5995a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - gast
    - beniget
    - nbformat
    - pyyaml
    - python-language-server
    - memestra

test:
  imports:
    - pyls_memestra

about:
  home: https://github.com/QuantStack/pyls-memestra/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Memestra plugin for the Python Language Server

extra:
  recipe-maintainers:
    - marimeireles
    - SylvainCorlay
